import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";
import slugify from "slugify";

// Note: 'cn' is generated by Shaqcn, do not modify ('cn' is for merging className)
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function slugifyLeadMagnet(title: string) {
  return slugify(title, {
    replacement: "-",
    strict: false,
    lower: true,
    trim: false, // no trim to allow users to type space at the end
  });
}
